auto: true
server: true
exclude: README.md, .gitignore
permalink: none
baseurl: 
url: http://baynode.github.com
hashtag: '#BayNode'
github_login: 'BayNode'
github_repo: 'baynode.github.com'
github_lanaguage: 'JavaScript'
